# Generated by Django 4.2.1 on 2023-06-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('reservation_data', models.CharField(max_length=255)),
                ('reservation_slot', models.IntegerField()),
            ],
        ),
    ]
