# Generated by Django 4.2.1 on 2023-06-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='reservation_data',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='reservation_slot',
            field=models.CharField(max_length=255),
        ),
    ]
